AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: 
  keywords-SAM

  SAM template for the keywords api

# Available top-level fields are listed in code completion
Globals:
  Function:
    Timeout: 3

# Add Resources Here: uncomment the following lines
Resources:
  GetKeyWordsFuntion:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/keywords
      Handler: app.handler
      Runtime: nodejs20.x
      FunctionUrlConfig:
        AuthType: NONE
      Architectures:
        - arm64
      Environment:
        Variables:
          OPENAI_API_KEY: ""  


Outputs:
  GetKeyWordsFuntion:
    Description: "Get Keywords Lambda Function ARN"
    Value: !GetAtt GetKeyWordsFuntion.Arn
