AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: 
  keywords-SAM

  SAM template for the keywords api

# Available top-level fields are listed in code completion
Globals:
  Function:
    Timeout: 3

# Add Resources Here: uncomment the following lines
Resources:
  GetKeyWordsFuntion:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: keywordsSam/
      Handler: app.handler
      Runtime: nodejs20.x
      FunctionUrlConfig:
        AuthType: NONE
      Architectures:
        - arm64
     
     

Outputs:

  HelloWorldFunction:
    Description: "Get Keywords Lambda Function ARN"
    Value: !GetAtt GetKeyWordsFuntion.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GetKeyWordsFuntionRole.Arn
