AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: 
  keywords-SAM

  SAM template for the keywords api

# Available top-level fields are listed in code completion
Globals:
  Function:
    Timeout: 3

# Add Resources Here: uncomment the following lines
Resources:
  GetKeyWordsFuntion:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: keywordsSam/
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
     

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  HelloWorldFunction:
    Description: "Get Keywords Lambda Function ARN"
    Value: !GetAtt GetKeyWordsFuntion.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GetKeyWordsFuntionRole.Arn
